Rsvp Li changes for yang model
open-traffic-generator/models-yang pull request #20
Opened 2022-10-13 10:42 UTC by SouravSinhaRoy

Rsvp Li changes for yang model

2022-10-14 10:41 UTC, apratimmukherjee requested changes

2022-10-14 10:41 UTC, apratimmukherjee commented on artifacts/open-traffic-generator-rsvp.txt
> +        |     +--ro egress-p2p-lsps-up?            otg-types:counter64
Do counters come in order specified here ? If yes, maybe we can shift the configured / up counts to the top ?

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "Each RSVP-TE router is identified by an arbitrary string
an abitrary  -> a unique

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "The number of received RSVP path messages.";
All message types are in lower case e.g. path to Path , path tear to Path Tear ? What  is the oc convention and in other gnmi specs for OTG ?

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        }
differentiator ; breaak -> break  ;   two LSPs which are part of the same tunnel 
a key -> the key

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        }
a key -> the key for this and below attributes.

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +              "The Setup time.";
Maybe we could exclude this for now. Otherwise, to be truly useful we need to define the format etc, (e.g. n ms from what -> container restart . last RSVP start etc. )

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +              "The Up time.";
in ms.

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "Index of object in the list.";
RRO sub-object in the list . Should we specify the order ? e.g. both ERO and RRO will have the nearest hop at the top of the list and the furthest hop at the end of the list,

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "The container for LLDP neighbor custom tlv state.";
RSVP-TE RRO sub-objects

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "IP router hop for RRO entry.";
IPv4 hop ( dont give router , it could be interface ip or loopback ip_)

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "Subobject flags for MPLS Label.";
I think flags is normally a list of enums in oc ( e.g ISIS flags ) , or could be a group of bools  , but we should avoid decimal value .

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "The container for LLDP neighbor custom tlv state.";
RSVP-TE ERO sub-object

2022-10-14 10:41 UTC, apratimmukherjee commented on models/rsvp/open-traffic-generator-rsvp.yang
> +       }
Does oc/spec allow 4 byte ; then data type should be uint32
Or need separate attribs for 2 byte and 4 byte

2022-10-14 11:46 UTC, SouravSinhaRoy commented on artifacts/open-traffic-generator-rsvp.txt
> +        |     +--ro egress-p2p-lsps-up?            otg-types:counter64
moved configured and up to top

2022-10-14 11:46 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "Each RSVP-TE router is identified by an arbitrary string
updated

2022-10-14 11:47 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "The number of received RSVP path messages.";
all stats are in lower case and also in the description the type of the packet is lower case

2022-10-14 11:48 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        }
updated

2022-10-14 11:48 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        }
updated

2022-10-14 11:48 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +              "The Setup time.";
removed

2022-10-14 11:49 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +              "The Up time.";
updated

2022-10-14 11:49 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "Index of object in the list.";
removed the specification of order in ero,updated

2022-10-14 11:49 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "The container for LLDP neighbor custom tlv state.";
updated

2022-10-14 11:50 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "IP router hop for RRO entry.";
updated

2022-10-14 11:50 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "Subobject flags for MPLS Label.";
oc doesn't specify enums.thinking of not keeping reported-flag currently

2022-10-14 11:50 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "The container for LLDP neighbor custom tlv state.";
updated

2022-10-14 11:51 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +       }
changed to uint32,oc has 4 bytes asn

2022-10-17 11:56 UTC, apratimmukherjee approved these changes
Bring back the description for ERO/RRO sub-object ordering. Rest looks good.

2022-10-17 12:03 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "Subobject flags for MPLS Label.";
removed flags

2022-10-17 12:03 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "Index of object in the list.";
added comments back

2022-10-19 09:52 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "A list of RSVP-TE Discovered LSPs.";
updated

2022-10-19 09:52 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +              "Reference to the reason for the last flap of this RSVP session.";
updated

2022-10-19 09:52 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +        "Index of object in the list.";
updated

2022-10-19 09:52 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +          "IP router hop for RRO entry.";
updated

2022-10-19 09:57 UTC, SouravSinhaRoy commented on models/rsvp/open-traffic-generator-rsvp.yang
> +              "Unkeyed list of MPLS RRO objects associated with the traffic engineering tunnel.";
user will know the index by the configuration he has done in dut, the rro list in learned should exactly match the one in configured,user can query and match based on a particular index

2022-10-19 10:55 UTC, PrasenjitAdhikary approved these changes

2022-12-02 06:59 UTC, merged